services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env
    secrets:
      - db_pw
      - db_rootpw
    volumes:
      - mariadb_store:/var/lib/mysql
    networks:
      - inc_network

volumes:
  mariadb_store:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mehmeyil/data/mariadb

secrets:
  db_pw:
    file: ../secrets/db_pw.txt
  db_rootpw:
    file: ../secrets/db_rootpw.txt

networks:
  inc_network:
    driver: bridge
