# services:
#   mariadb:
#     build: ./requirements/mariadb
#     image: mariadb
#     container_name: mariadb
#     restart: always
#     ports:
#       - "3306:3306"
#     env_file:
#       - .env
#     secrets:
#       - db_pw
#       - db_rootpw
#     volumes:
#       - mariadb_store:/var/lib/mysql
#     networks:
#       - inc_network

# volumes:
#   mariadb_store:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: /home/mehmeyil/data/mariadb

# secrets:
#   db_pw:
#     file: ../secrets/db_pw.txt
#   db_rootpw:
#     file: ../secrets/db_rootpw.txt

# networks:
#   inc_network:
#     driver: bridge

services:
  nginx:
    build: ./srcs/requirements/nginx
    ports:
      - "443:443"
    networks:
      - app_network
    depends_on:
      - wordpress
    restart: unless-stopped
    secrets:
      - ssl_cert
      - ssl_key

  wordpress:
    build: ./srcs/requirements/wordpress
    networks:
      - app_network
    volumes:
      - wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER_FILE: /run/secrets/db_user
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_pw
      WORDPRESS_DB_NAME: wordpress
    secrets:
      - db_pw
      - db_user
      - wp_adminpw
    depends_on:
      - mariadb
    restart: unless-stopped

  mariadb:
    build: ./srcs/requirements/mariadb
    networks:
      - app_network
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_rootpw
      MYSQL_DATABASE: wordpress
      MYSQL_USER_FILE: /run/secrets/db_user
      MYSQL_PASSWORD_FILE: /run/secrets/db_pw
    secrets:
      - db_rootpw
      - db_pw
      - db_user
    restart: unless-stopped

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/wordpress
      o: bind
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/mariadb
      o: bind

networks:
  app_network:
    driver: bridge

secrets:
  db_rootpw:
    file: ./secrets/db_rootpw.txt
  db_pw:
    file: ./secrets/db_pw.txt
  db_user:
    file: ./secrets/db_user.txt
  wp_adminpw:
    file: ./secrets/wp_adminpw.txt
  ssl_cert:
    file: ./srcs/requirements/nginx/ssl/mehmeyil.42.fr.crt
  ssl_key:
    file: ./srcs/requirements/nginx/ssl/mehmeyil.42.fr.key
